// dither-kit-svelte/Bar.svelte
<script lang="ts">
  import { untrack, type Snippet } from "svelte"
  import {
    registerSeries,
    useChartPart,
    type SeriesSpec,
    type StrokeVariant,
    type VariantInput,
  } from "./chart-context"
  import { setSeries } from "./series-context"

  type Props = {
    dataKey: string
    variant?: VariantInput
    strokeVariant?: StrokeVariant
    isClickable?: boolean
    opacity?: number
    children?: Snippet
  }

  let {
    dataKey,
    variant = "gradient",
    strokeVariant = "solid",
    isClickable = false,
    opacity = 1,
    children,
  }: Props = $props()

  const ctx = useChartPart("Bar", "bar")

  untrack(() => {
    if ((import.meta as { env?: { DEV?: boolean } }).env?.DEV && !ctx.config[dataKey]) {
      console.warn(
        `<Bar dataKey="${dataKey}" />: "${dataKey}" is not in the chart \`config\`. Add it so the series has a colour and label.`
      )
    }
  })

  setSeries({
    get dataKey() {
      return dataKey
    },
    get seed() {
      return ctx.seedOf(dataKey)
    },
    get dimmed() {
      return ctx.selectedDataKey !== null && ctx.selectedDataKey !== dataKey
    },
  })

  const spec: SeriesSpec = $derived({ dataKey, kind: "bar", variant, strokeVariant, opacity })
  const band = $derived(ctx.bands[dataKey])
  const si = $derived(ctx.configKeys.indexOf(dataKey))
  const rects = $derived.by(() => {
    if (!isClickable || !band) return []
    const n = ctx.configKeys.length
    return band.map((b, i) => {
      const slot = ctx.barSlot(i, si, n)
      const top = ctx.y(b[1])
      const base = ctx.y(b[0])
      return {
        x: slot.x,
        y: Math.min(top, base),
        width: slot.width,
        height: Math.abs(base - top),
      }
    })
  })

  function onClick() {
    ctx.selectDataKey(ctx.selectedDataKey === dataKey ? null : dataKey)
  }
</script>

<g use:registerSeries={{ ctx, spec }}>
  {#if ctx.ready && band}
    {#each rects as r, i (i)}
      <!-- svelte-ignore a11y_no_static_element_interactions (bar hit-area is a pointer convenience; the Legend is the keyboard-accessible selector) -->
      <!-- svelte-ignore a11y_click_events_have_key_events (bar hit-area is a pointer convenience; the Legend is the keyboard-accessible selector) -->
      <rect
        x={r.x}
        y={r.y}
        width={r.width}
        height={r.height}
        fill="transparent"
        style="cursor: pointer"
        onclick={onClick}
      />
    {/each}
    {@render children?.()}
  {/if}
</g>

// dither-kit/Bar.vue
<script setup lang="ts">
import { computed, onBeforeUnmount, provide, watch } from "vue"
import {
  type VariantInput,
  type StrokeVariant,
  useChartPart,
} from "./chart-context"
import { SeriesKey } from "./series-context"

const props = withDefaults(
  defineProps<{
    dataKey: string
    variant?: VariantInput
    strokeVariant?: StrokeVariant
    isClickable?: boolean
  }>(),
  { variant: "gradient", strokeVariant: "solid", isClickable: false }
)

const ctx = useChartPart("Bar", "bar")

if (import.meta.env.DEV && !ctx.config[props.dataKey]) {
  console.warn(
    `<Bar dataKey="${props.dataKey}" />: "${props.dataKey}" is not in the chart \`config\`. Add it so the series has a colour and label.`
  )
}

watch(
  () => [props.dataKey, props.variant, props.strokeVariant] as const,
  ([dataKey, variant, strokeVariant]) =>
    ctx.registerSeries({ dataKey, kind: "bar", variant, strokeVariant }),
  { immediate: true }
)
onBeforeUnmount(() => ctx.unregisterSeries(props.dataKey))

provide(SeriesKey, {
  dataKey: props.dataKey,
  get seed() {
    return ctx.seedOf(props.dataKey)
  },
  get dimmed() {
    return ctx.selectedDataKey !== null && ctx.selectedDataKey !== props.dataKey
  },
})

const band = computed(() => ctx.bands[props.dataKey])
const si = computed(() => ctx.configKeys.indexOf(props.dataKey))
const rects = computed(() => {
  if (!props.isClickable || !band.value) return []
  const n = ctx.configKeys.length
  return band.value.map((b, i) => {
    const slot = ctx.barSlot(i, si.value, n)
    const top = ctx.y(b[1])
    const base = ctx.y(b[0])
    return {
      x: slot.x,
      y: Math.min(top, base),
      width: slot.width,
      height: Math.abs(base - top),
    }
  })
})

function onClick() {
  ctx.selectDataKey(ctx.selectedDataKey === props.dataKey ? null : props.dataKey)
}
</script>

<template>
  <g v-if="ctx.ready && band">
    <rect
      v-for="(r, i) in rects"
      :key="i"
      :x="r.x"
      :y="r.y"
      :width="r.width"
      :height="r.height"
      fill="transparent"
      style="cursor: pointer"
      @click="onClick"
    />
    <slot />
  </g>
</template>
