// dither-kit-svelte/DitherStepper.svelte
<script lang="ts" module>
  export type Step = { label: string; hint?: string }
</script>

<script lang="ts">
  import { cn } from "./lib"
  import DitherSeparator from "./DitherSeparator.svelte"

  type Props = {
    steps: Step[]
    current: number // index of the active step
    class?: string
  }

  let { steps, current, class: className }: Props = $props()

  const stepState = (i: number) =>
    i < current ? "done" : i === current ? "active" : "todo"
</script>

<!-- svelte-ignore a11y_no_redundant_roles (list-style:none can drop list semantics; role=list restores them) -->
<ol class={cn("flex items-start", className)} role="list" aria-label="Progress">
  {#each steps as s, i (i)}
    <li
      class="flex flex-1 flex-col items-center"
      aria-current={i === current ? "step" : undefined}
    >
      <div class="flex w-full items-center">
        {#if i > 0}
          <DitherSeparator
            class={cn("flex-1", stepState(i) === "todo" ? "opacity-30" : "")}
          />
        {:else}
          <span class="flex-1"></span>
        {/if}
        <span
          class={cn(
            "inline-flex size-7 shrink-0 items-center justify-center rounded-full border text-[11px] tabular-nums transition-colors",
            stepState(i) === "done" && "border-foreground/30 bg-foreground/10 text-foreground",
            stepState(i) === "active" && "border-foreground bg-background text-foreground",
            stepState(i) === "todo" && "border-border text-muted-foreground"
          )}
        >
          {#if stepState(i) === "done"}
            <svg
              viewBox="0 0 24 24"
              class="size-3.5"
              fill="none"
              stroke="currentColor"
              stroke-width="3"
            >
              <path d="M5 12l5 5L20 7" />
            </svg>
          {:else}
            {i + 1}
          {/if}
        </span>
        {#if i < steps.length - 1}
          <DitherSeparator
            class={cn(
              "flex-1",
              stepState(i + 1) === "todo" && stepState(i) !== "active"
                ? "opacity-30"
                : stepState(i) === "todo"
                  ? "opacity-30"
                  : ""
            )}
          />
        {:else}
          <span class="flex-1"></span>
        {/if}
      </div>
      <span
        class={cn(
          "mt-2 text-center text-[12px]",
          i === current ? "text-foreground" : "text-muted-foreground"
        )}>{s.label}</span
      >
      {#if s.hint}
        <span class="text-center text-[11px] text-muted-foreground/60">{s.hint}</span>
      {/if}
    </li>
  {/each}
</ol>

// dither-kit/DitherStepper.vue
<script lang="ts">
export type Step = { label: string; hint?: string }
</script>

<script setup lang="ts">
import { cn } from "./lib"
import DitherSeparator from "./DitherSeparator.vue"

const props = withDefaults(
  defineProps<{
    steps: Step[]
    current: number // index of the active step
    class?: string
  }>(),
  {}
)

const state = (i: number) => (i < props.current ? "done" : i === props.current ? "active" : "todo")
</script>

<template>
  <ol :class="cn('flex items-start', props.class)" role="list" aria-label="Progress">
    <li
      v-for="(s, i) in steps"
      :key="i"
      class="flex flex-1 flex-col items-center"
      :aria-current="i === current ? 'step' : undefined"
    >
      <div class="flex w-full items-center">
        <DitherSeparator v-if="i > 0" class="flex-1" :class="state(i) === 'todo' ? 'opacity-30' : ''" />
        <span v-else class="flex-1" />
        <span
          :class="
            cn(
              'inline-flex size-7 shrink-0 items-center justify-center rounded-full border text-[11px] tabular-nums transition-colors',
              state(i) === 'done' && 'border-foreground/30 bg-foreground/10 text-foreground',
              state(i) === 'active' && 'border-foreground bg-background text-foreground',
              state(i) === 'todo' && 'border-border text-muted-foreground'
            )
          "
        >
          <svg v-if="state(i) === 'done'" viewBox="0 0 24 24" class="size-3.5" fill="none" stroke="currentColor" stroke-width="3">
            <path d="M5 12l5 5L20 7" />
          </svg>
          <template v-else>{{ i + 1 }}</template>
        </span>
        <DitherSeparator
          v-if="i < steps.length - 1"
          class="flex-1"
          :class="state(i + 1) === 'todo' && state(i) !== 'active' ? 'opacity-30' : state(i) === 'todo' ? 'opacity-30' : ''"
        />
        <span v-else class="flex-1" />
      </div>
      <span
        :class="
          cn('mt-2 text-center text-[12px]', i === current ? 'text-foreground' : 'text-muted-foreground')
        "
        >{{ s.label }}</span
      >
      <span v-if="s.hint" class="text-center text-[11px] text-muted-foreground/60">{{ s.hint }}</span>
    </li>
  </ol>
</template>
