// dither-kit-svelte/text/GradualBlur.svelte
<script lang="ts">
  import type { Snippet } from "svelte"
  import { cn } from "../runtime/lib"

  type Props = {
    position?: "bottom" | "top"
    height?: number
    strength?: number
    class?: string
    children?: Snippet
  }

  let {
    position = "bottom",
    height = 96,
    strength = 4,
    class: className,
    children,
  }: Props = $props()

  // Progressive edge blur (iOS-style): a masked backdrop-filter strip so content
  // dissolves toward the chosen edge.
  const mask = $derived(
    position === "top"
      ? "linear-gradient(to bottom, black, transparent)"
      : "linear-gradient(to top, black, transparent)"
  )
</script>

<div class={cn("relative", className)}>
  {@render children?.()}
  <div
    class="pointer-events-none absolute inset-x-0 {position === 'top' ? 'top-0' : 'bottom-0'}"
    style:height="{height}px"
    style:backdrop-filter="blur({strength}px)"
    style:-webkit-backdrop-filter="blur({strength}px)"
    style:mask-image={mask}
    style:-webkit-mask-image={mask}
  ></div>
</div>

// dither-kit/GradualBlur.vue
<script setup lang="ts">
import { computed } from "vue"
import { cn } from "./lib"

const props = withDefaults(
  defineProps<{
    position?: "bottom" | "top"
    height?: number
    strength?: number
    class?: string
  }>(),
  { position: "bottom", height: 96, strength: 4 }
)

// Progressive edge blur (iOS-style): a masked backdrop-filter strip so content
// dissolves toward the chosen edge.
const mask = computed(() =>
  props.position === "top"
    ? "linear-gradient(to bottom, black, transparent)"
    : "linear-gradient(to top, black, transparent)"
)
</script>

<template>
  <div :class="cn('relative', props.class)">
    <slot />
    <div
      class="pointer-events-none absolute inset-x-0"
      :class="props.position === 'top' ? 'top-0' : 'bottom-0'"
      :style="{
        height: `${props.height}px`,
        backdropFilter: `blur(${props.strength}px)`,
        WebkitBackdropFilter: `blur(${props.strength}px)`,
        maskImage: mask,
        WebkitMaskImage: mask,
      }"
    />
  </div>
</template>
