// dither-kit-svelte/charts/Pie.svelte
<script lang="ts">
  import type { VariantInput } from "./chart-context"
  import { registerVariant, usePolarPart } from "./polar-context"

  type Props = { variant?: VariantInput }
  let { variant = "gradient" }: Props = $props()

  const ctx = usePolarPart("Pie", "pie")
</script>

<!-- Slices are painted on the canvas; this part only registers the variant. -->
<g use:registerVariant={{ ctx, key: "*", variant }}></g>

// dither-kit/Pie.vue
<script setup lang="ts">
import { onBeforeUnmount, watch } from "vue"
import type { VariantInput } from "./chart-context"
import { usePolarPart } from "./polar-context"

const props = withDefaults(
  defineProps<{ variant?: VariantInput }>(),
  { variant: "gradient" }
)

const ctx = usePolarPart("Pie", "pie")

watch(
  () => props.variant,
  (variant) => ctx.registerVariant("*", variant),
  { immediate: true }
)
onBeforeUnmount(() => ctx.unregisterVariant("*"))
</script>

<template>
  <!-- Slices are painted on the canvas; this part only registers the variant. -->
</template>
