// dither-kit-svelte/TrueFocus.svelte
<script lang="ts">
  import { onMount } from "svelte"
  import { cn } from "./lib"
  import { pixelPrefersReducedMotion } from "./pixel"

  type Props = {
    text?: string
    interval?: number
    blur?: number
    class?: string
  }

  let { text = "True focus mode", interval = 1400, blur = 5, class: className }: Props = $props()

  const words = $derived(text.split(/\s+/).filter(Boolean))
  let active = $state(0)

  onMount(() => {
    if (pixelPrefersReducedMotion() || words.length < 2) return
    const timer = window.setInterval(() => {
      active = (active + 1) % words.length
    }, Math.max(300, interval))
    return () => clearInterval(timer)
  })
</script>

<span class={cn("inline-flex flex-wrap gap-x-[0.35em] gap-y-1", className)} aria-label={text}>
  {#each words as w, i (i)}
    <span
      aria-hidden="true"
      class="dither-focus-word inline-block transition-[filter,opacity] duration-500"
      style:filter={i === active ? "blur(0)" : `blur(${blur}px)`}
      style:opacity={i === active ? 1 : 0.5}>{w}</span>
  {/each}
</span>

// dither-kit/TrueFocus.vue
<script setup lang="ts">
import { computed, onBeforeUnmount, onMounted, ref } from "vue"
import { cn } from "./lib"
import { pixelPrefersReducedMotion } from "./pixel"

const props = withDefaults(
  defineProps<{
    text?: string
    interval?: number
    blur?: number
    class?: string
  }>(),
  { text: "True focus mode", interval: 1400, blur: 5 }
)

const words = computed(() => props.text.split(/\s+/).filter(Boolean))
const active = ref(0)
let timer = 0

onMounted(() => {
  if (pixelPrefersReducedMotion() || words.value.length < 2) return
  timer = window.setInterval(() => {
    active.value = (active.value + 1) % words.value.length
  }, Math.max(300, props.interval))
})
onBeforeUnmount(() => clearInterval(timer))
</script>

<template>
  <span :class="cn('inline-flex flex-wrap gap-x-[0.35em] gap-y-1', props.class)" :aria-label="props.text">
    <span
      v-for="(w, i) in words"
      :key="i"
      aria-hidden="true"
      class="dither-focus-word inline-block transition-[filter,opacity] duration-500"
      :style="{ filter: i === active ? 'blur(0)' : `blur(${props.blur}px)`, opacity: i === active ? 1 : 0.5 }"
    >{{ w }}</span>
  </span>
</template>
