// dither-kit/Area.vue
<script setup lang="ts">
import type { StrokeVariant, VariantInput } from "./chart-context"
import CartesianSeries from "./CartesianSeries.vue"

defineProps<{
  dataKey: string
  variant?: VariantInput
  strokeVariant?: StrokeVariant
  isClickable?: boolean
}>()
</script>

<template>
  <CartesianSeries part="Area" kind="area" v-bind="$props">
    <slot />
  </CartesianSeries>
</template>

// dither-kit-svelte/charts/Area.svelte
<script lang="ts">
  import type { Snippet } from "svelte"
  import CartesianSeries from "./CartesianSeries.svelte"
  import type { StrokeVariant, VariantInput } from "./chart-context"

  type Props = {
    dataKey: string
    variant?: VariantInput
    strokeVariant?: StrokeVariant
    isClickable?: boolean
    opacity?: number
    children?: Snippet
  }

  let { children, ...rest }: Props = $props()
</script>

<CartesianSeries part="Area" kind="area" {...rest}>
  {@render children?.()}
</CartesianSeries>
