// dither-kit/RotatingText.vue
<script setup lang="ts">
import { computed, onBeforeUnmount, onMounted, ref, watch } from "vue"
import { cn } from "./lib"

const props = withDefaults(
  defineProps<{
    texts?: string[]
    interval?: number
    class?: string
  }>(),
  { texts: () => ["Vue", "canvas", "dither"], interval: 2000 }
)

const list = computed(() => (props.texts.length ? props.texts : [""]))
const idx = ref(0)
let timer = 0

function start() {
  clearInterval(timer)
  if (list.value.length < 2) return
  timer = window.setInterval(() => {
    idx.value = (idx.value + 1) % list.value.length
  }, Math.max(300, props.interval))
}

onMounted(start)
watch(() => [props.texts, props.interval], () => { idx.value = 0; start() })
onBeforeUnmount(() => clearInterval(timer))
</script>

<template>
  <span :class="cn('dither-rotating', props.class)">
    <Transition name="dither-rot" mode="out-in">
      <span :key="idx" class="inline-block">{{ list[idx] }}</span>
    </Transition>
  </span>
</template>

<style scoped>
.dither-rotating {
  display: inline-block;
  overflow: hidden;
  vertical-align: bottom;
}
.dither-rot-enter-active,
.dither-rot-leave-active {
  transition: opacity 300ms cubic-bezier(0.2, 0, 0, 1), transform 300ms cubic-bezier(0.2, 0, 0, 1);
}
.dither-rot-enter-from {
  opacity: 0;
  transform: translateY(0.7em);
}
.dither-rot-leave-to {
  opacity: 0;
  transform: translateY(-0.7em);
}
@media (prefers-reduced-motion: reduce) {
  .dither-rot-enter-active,
  .dither-rot-leave-active {
    transition: opacity 200ms;
  }
  .dither-rot-enter-from,
  .dither-rot-leave-to {
    transform: none;
  }
}
</style>

// dither-kit-svelte/text/RotatingText.svelte
<script lang="ts">
  import { fly } from "svelte/transition"
  import { cn } from "../runtime/lib"
  import { pixelPrefersReducedMotion } from "../engine/pixel"

  type Props = {
    texts?: string[]
    interval?: number
    class?: string
  }

  let { texts = ["Vue", "canvas", "dither"], interval = 2000, class: className }: Props = $props()

  const list = $derived(texts.length ? texts : [""])
  let idx = $state(0)

  // Reduced-motion collapses the vertical slide to a plain fade.
  const rm = pixelPrefersReducedMotion()
  const flyIn = rm ? { y: 0, duration: 200 } : { y: 10, duration: 300 }
  const flyOut = rm ? { y: 0, duration: 200 } : { y: -10, duration: 300 }

  // Timer lives in an action so a change to `texts`/`interval` (encoded in the
  // key) restarts the cycle and resets the index — the guardrail-clean stand-in
  // for Vue's watch, with no `$effect`.
  function rotate(_node: HTMLElement, _key: string) {
    let timer = 0
    function start() {
      clearInterval(timer)
      idx = 0
      if (list.length < 2) return
      timer = window.setInterval(() => {
        idx = (idx + 1) % list.length
      }, Math.max(300, interval))
    }
    start()
    return {
      update() {
        start()
      },
      destroy() {
        clearInterval(timer)
      },
    }
  }
</script>

<span use:rotate={`${list.length}|${interval}`} class={cn("dither-rotating", className)}>
  {#key idx}
    <span class="inline-block" in:fly={flyIn} out:fly={flyOut}>{list[idx]}</span>
  {/key}
</span>

<style>
  .dither-rotating {
    display: inline-block;
    overflow: hidden;
    vertical-align: bottom;
  }
</style>
