// dither-kit/Shuffle.vue
<script setup lang="ts">
import { computed } from "vue"
import { cn } from "./lib"

const props = withDefaults(
  defineProps<{
    text?: string
    stagger?: number
    duration?: number
    replayToken?: number
    class?: string
  }>(),
  { text: "Shuffle in", stagger: 55, duration: 650 }
)

// Deterministic per-character random offset so the shuffle is stable per render.
function seeded(i: number, salt: number) {
  const s = Math.sin(i * 12.9898 + salt * 78.233) * 43758.5453
  return s - Math.floor(s)
}
const chars = computed(() =>
  [...props.text].map((ch, i) => ({
    ch: ch === " " ? "\u00a0" : ch,
    dx: (seeded(i, 1) - 0.5) * 2, // -1..1 em
    dy: (seeded(i, 2) - 0.5) * 1.4,
    rot: (seeded(i, 3) - 0.5) * 40,
  }))
)
const runKey = computed(() => `${props.text}-${props.replayToken ?? 0}`)
</script>

<template>
  <span :key="runKey" :class="cn('inline-block', props.class)" :aria-label="props.text">
    <span
      v-for="(c, i) in chars"
      :key="i"
      aria-hidden="true"
      class="dither-shuffle-char"
      :style="{
        animationDelay: `${i * props.stagger}ms`,
        animationDuration: `${props.duration}ms`,
        '--dx': `${c.dx}em`,
        '--dy': `${c.dy}em`,
        '--rot': `${c.rot}deg`,
      }"
    >{{ c.ch }}</span>
  </span>
</template>

<style scoped>
.dither-shuffle-char {
  display: inline-block;
  white-space: pre;
  animation: dither-shuffle-in cubic-bezier(0.2, 0.8, 0.2, 1) both;
  will-change: transform, opacity;
}
@keyframes dither-shuffle-in {
  from {
    opacity: 0;
    transform: translate(var(--dx), var(--dy)) rotate(var(--rot));
  }
  to {
    opacity: 1;
    transform: none;
  }
}
@media (prefers-reduced-motion: reduce) {
  .dither-shuffle-char {
    animation: none;
  }
}
</style>

// dither-kit-svelte/text/Shuffle.svelte
<script lang="ts">
  import { cn } from "../runtime/lib"

  type Props = {
    text?: string
    stagger?: number
    duration?: number
    replayToken?: number
    class?: string
  }

  let { text = "Shuffle in", stagger = 55, duration = 650, replayToken, class: className }: Props = $props()

  // Deterministic per-character random offset so the shuffle is stable per render.
  function seeded(i: number, salt: number) {
    const s = Math.sin(i * 12.9898 + salt * 78.233) * 43758.5453
    return s - Math.floor(s)
  }
  const chars = $derived(
    [...text].map((ch, i) => ({
      ch: ch === " " ? "\u00a0" : ch,
      dx: (seeded(i, 1) - 0.5) * 2, // -1..1 em
      dy: (seeded(i, 2) - 0.5) * 1.4,
      rot: (seeded(i, 3) - 0.5) * 40,
    }))
  )
  const runKey = $derived(`${text}-${replayToken ?? 0}`)
</script>

{#key runKey}
  <span class={cn("inline-block", className)} aria-label={text}>
    {#each chars as c, i (i)}
      <span
        aria-hidden="true"
        class="dither-shuffle-char"
        style:animation-delay={`${i * stagger}ms`}
        style:animation-duration={`${duration}ms`}
        style:--dx={`${c.dx}em`}
        style:--dy={`${c.dy}em`}
        style:--rot={`${c.rot}deg`}
      >{c.ch}</span>
    {/each}
  </span>
{/key}

<style>
  .dither-shuffle-char {
    display: inline-block;
    white-space: pre;
    animation: dither-shuffle-in cubic-bezier(0.2, 0.8, 0.2, 1) both;
    will-change: transform, opacity;
  }
  @keyframes dither-shuffle-in {
    from {
      opacity: 0;
      transform: translate(var(--dx), var(--dy)) rotate(var(--rot));
    }
    to {
      opacity: 1;
      transform: none;
    }
  }
  @media (prefers-reduced-motion: reduce) {
    .dither-shuffle-char {
      animation: none;
    }
  }
</style>
