// dither-kit/DitherTextarea.vue
<script setup lang="ts">
import { computed } from "vue"
import { cn } from "./lib"
import { cssColor } from "./palette"
import { CONTROL, useField } from "./control"

defineOptions({ inheritAttrs: false })

const props = withDefaults(defineProps<{
  modelValue?: string
  placeholder?: string
  rows?: number
  resize?: "none" | "vertical" | "horizontal" | "both"
  disabled?: boolean
  readonly?: boolean
  invalid?: boolean
  class?: string
}>(), { modelValue: "", rows: 4, resize: "vertical", disabled: false, readonly: false, invalid: false })
const emit = defineEmits<{ "update:modelValue": [value: string] }>()
const field = useField()
const invalid = computed(() => props.invalid || field?.invalid.value || false)
</script>

<template>
  <textarea
    :id="($attrs.id as string | undefined) ?? field?.controlId.value"
    :value="props.modelValue"
    :placeholder="props.placeholder"
    :rows="props.rows"
    :disabled="props.disabled"
    :readonly="props.readonly"
    :aria-invalid="invalid || undefined"
    :aria-describedby="($attrs['aria-describedby'] as string | undefined) ?? field?.describedBy.value"
    :style="{ resize: props.resize, ...(invalid ? { borderColor: cssColor('red') } : {}) }"
    :class="cn(CONTROL, 'block w-full leading-relaxed read-only:cursor-default read-only:bg-card/40 read-only:text-muted-foreground', props.class)"
    v-bind="$attrs"
    @input="emit('update:modelValue', ($event.target as HTMLTextAreaElement).value)"
  />
</template>

// dither-kit-svelte/controls/DitherTextarea.svelte
<script lang="ts">
  import type { HTMLTextareaAttributes } from "svelte/elements"
  import { cn } from "../runtime/lib"
  import { cssColor } from "../engine/palette"
  import { CONTROL, useField } from "../runtime/control"

  type Props = {
    value?: string
    resize?: "none" | "vertical" | "horizontal" | "both"
    invalid?: boolean
    class?: string
  } & Omit<HTMLTextareaAttributes, "value" | "class">

  let {
    value = $bindable(""),
    rows = 4,
    resize = "vertical",
    invalid: invalidProp = false,
    class: className,
    id,
    ...rest
  }: Props = $props()

  const field = useField()
  const invalid = $derived(invalidProp || field?.invalid || false)
  const describedBy = $derived(
    (rest["aria-describedby"] as string | undefined) ?? field?.describedBy
  )
</script>

<textarea
  bind:value
  {rows}
  id={id ?? field?.controlId}
  aria-invalid={invalid || undefined}
  aria-describedby={describedBy}
  style:resize
  style:border-color={invalid ? cssColor("red") : undefined}
  class={cn(
    CONTROL,
    "block w-full leading-relaxed read-only:cursor-default read-only:bg-card/40 read-only:text-muted-foreground",
    className
  )}
  {...rest}
></textarea>
