// dither-kit/DitherCheckboxGroup.vue
<script setup lang="ts">
import DitherCheckbox from "./DitherCheckbox.vue"
import type { Option } from "./DitherSelect.vue"
import { cn } from "./lib"
import type { PixelColor } from "./pixel"

const props = withDefaults(
  defineProps<{
    options: Option[]
    modelValue: string[]
    color?: PixelColor
    label?: string
    class?: string
  }>(),
  { color: "blue" }
)

const emit = defineEmits<{ (e: "update:modelValue", value: string[]): void }>()

function toggle(value: string, on: boolean) {
  emit(
    "update:modelValue",
    on
      ? [...props.modelValue, value]
      : props.modelValue.filter((v) => v !== value)
  )
}
</script>

<template>
  <div role="group" :aria-label="props.label" :class="cn('grid gap-3', props.class)">
    <DitherCheckbox
      v-for="o in props.options"
      :key="o.value"
      :model-value="props.modelValue.includes(o.value)"
      :color="props.color"
      :disabled="o.disabled"
      @update:model-value="(on) => toggle(o.value, on)"
    >
      {{ o.label }}
    </DitherCheckbox>
  </div>
</template>

// dither-kit-svelte/controls/DitherCheckboxGroup.svelte
<script lang="ts">
  import DitherCheckbox from "./DitherCheckbox.svelte"
  import type { Option } from "./DitherSelect.svelte"
  import { cn } from "../runtime/lib"
  import type { PixelColor } from "../engine/pixel"

  type Props = {
    options: Option[]
    value?: string[]
    color?: PixelColor
    label?: string
    class?: string
  }

  let {
    options,
    value = $bindable<string[]>([]),
    color = "blue",
    label,
    class: className,
  }: Props = $props()

  function toggle(v: string, on: boolean) {
    value = on ? [...value, v] : value.filter((x) => x !== v)
  }
</script>

<div role="group" aria-label={label} class={cn("grid gap-3", className)}>
  {#each options as o (o.value)}
    <DitherCheckbox
      bind:value={() => value.includes(o.value), (on) => toggle(o.value, on)}
      {color}
      disabled={o.disabled}
    >
      {o.label}
    </DitherCheckbox>
  {/each}
</div>
